#pragma once

namespace dl
{
enum KeyModifier
{
  DL_KEY_MODIFIER_NONE = 0x0000,
  DL_KEY_MODIFIER_LSHIFT = 0x0001,
  DL_KEY_MODIFIER_RSHIFT = 0x0002,
  DL_KEY_MODIFIER_LCTRL = 0x0040,
  DL_KEY_MODIFIER_RCTRL = 0x0080,
  DL_KEY_MODIFIER_LALT = 0x0100,
  DL_KEY_MODIFIER_RALT = 0x0200,
  DL_KEY_MODIFIER_LMETA = 0x0400,
  DL_KEY_MODIFIER_RMETA = 0x0800,
  DL_KEY_MODIFIER_NUM = 0x1000,
  DL_KEY_MODIFIER_CAPS = 0x2000,
  DL_KEY_MODIFIER_MODE = 0x4000,
};

#define DL_KEY_MODIFIER_SHIFT (DL_KEY_MODIFIER_LSHIFT | DL_KEY_MODIFIER_RSHIFT)
#define DL_KEY_MODIFIER_UPPERCASE (DL_KEY_MODIFIER_SHIFT | DL_KEY_MODIFIER_CAPS)
#define DL_KEY_MODIFIER_ALT (DL_KEY_MODIFIER_LALT | DL_KEY_MODIFIER_RALT)
#define DL_KEY_MODIFIER_META (DL_KEY_MODIFIER_LMETA | DL_KEY_MODIFIER_RMETA)

// For macos only, also use META key as CTRL
#ifdef __APPLE__
#define DL_KEY_MODIFIER_CTRL (DL_KEY_MODIFIER_LCTRL | DL_KEY_MODIFIER_RCTRL | DL_KEY_MODIFIER_META)
#else
#define DL_KEY_MODIFIER_CTRL (DL_KEY_MODIFIER_LCTRL | DL_KEY_MODIFIER_RCTRL)
#endif

}  // namespace dl
